language: node_js
node_js:
  - "7"
before_install:
  - "cd my-app"
install:
  - npm install
before_deploy:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
